import { StarShapeVariant } from "@/components/atoms/star-shape";

export interface ShapeConfig {
  id: string;
  variant: StarShapeVariant;
  color: "primary" | "secondary" | "accent";
  size: number;
  startY: number;
  startX: number;
  waveAmplitude: number;
  waveFrequency: number;
  phaseOffset: number;
  scrollDistance: number;
  rotationDirection: 1 | -1;
  rotationPauses: number[];
  maxRotation: number;
  floatDuration: number;
  floatAmplitude: number;
  floatDelay: number;
  breatheMin: number;
  breatheMax: number;
  breatheDuration: number;
  glowIntensity: number;
}

export const shapeConfigs: ShapeConfig[] = [
  {
    id: "shape-1",
    variant: "gooey-star",
    color: "primary",
    size: 80,
    startY: 15,
    startX: 20,
    waveAmplitude: 120,
    waveFrequency: 2.5,
    phaseOffset: 0,
    scrollDistance: 65,
    rotationDirection: 1,
    rotationPauses: [0.3, 0.6],
    maxRotation: 360,
    floatDuration: 4.5,
    floatAmplitude: 18,
    floatDelay: 0,
    breatheMin: 0.92,
    breatheMax: 1.08,
    breatheDuration: 5,
    glowIntensity: 0.7,
  },
  {
    id: "shape-2",
    variant: "soft-star",
    color: "accent",
    size: 65,
    startY: 35,
    startX: 75,
    waveAmplitude: 100,
    waveFrequency: 3,
    phaseOffset: Math.PI / 3,
    scrollDistance: 55,
    rotationDirection: -1,
    rotationPauses: [0.25, 0.55, 0.8],
    maxRotation: 270,
    floatDuration: 5.2,
    floatAmplitude: 22,
    floatDelay: 0.8,
    breatheMin: 0.94,
    breatheMax: 1.06,
    breatheDuration: 4.5,
    glowIntensity: 0.65,
  },
  {
    id: "shape-3",
    variant: "four-point",
    color: "secondary",
    size: 55,
    startY: 60,
    startX: 35,
    waveAmplitude: 80,
    waveFrequency: 2,
    phaseOffset: Math.PI / 2,
    scrollDistance: 45,
    rotationDirection: 1,
    rotationPauses: [0.4, 0.7],
    maxRotation: 180,
    floatDuration: 3.8,
    floatAmplitude: 15,
    floatDelay: 1.5,
    breatheMin: 0.9,
    breatheMax: 1.1,
    breatheDuration: 6,
    glowIntensity: 0.6,
  },
  {
    id: "shape-4",
    variant: "clover",
    color: "primary",
    size: 70,
    startY: 80,
    startX: 60,
    waveAmplitude: 140,
    waveFrequency: 1.8,
    phaseOffset: Math.PI,
    scrollDistance: 50,
    rotationDirection: -1,
    rotationPauses: [0.2, 0.5, 0.85],
    maxRotation: 320,
    floatDuration: 4.8,
    floatAmplitude: 20,
    floatDelay: 0.5,
    breatheMin: 0.93,
    breatheMax: 1.07,
    breatheDuration: 5.5,
    glowIntensity: 0.75,
  },
  {
    id: "shape-5",
    variant: "pinwheel",
    color: "secondary",
    size: 60,
    startY: 175,
    startX: 15,
    waveAmplitude: 110,
    waveFrequency: 2.2,
    phaseOffset: Math.PI / 4,
    scrollDistance: 60,
    rotationDirection: 1,
    rotationPauses: [0.3, 0.6],
    maxRotation: 300,
    floatDuration: 4.6,
    floatAmplitude: 17,
    floatDelay: 0.4,
    breatheMin: 0.93,
    breatheMax: 1.07,
    breatheDuration: 5,
    glowIntensity: 0.6,
  },
  {
    id: "shape-6",
    variant: "four-point",
    color: "accent",
    size: 50,
    startY: 225,
    startX: 80,
    waveAmplitude: 90,
    waveFrequency: 2.8,
    phaseOffset: Math.PI / 6,
    scrollDistance: 48,
    rotationDirection: -1,
    rotationPauses: [0.25, 0.55],
    maxRotation: 180,
    floatDuration: 3.9,
    floatAmplitude: 14,
    floatDelay: 0.9,
    breatheMin: 0.95,
    breatheMax: 1.05,
    breatheDuration: 4.8,
    glowIntensity: 0.55,
  },
  {
    id: "shape-7",
    variant: "soft-star",
    color: "primary",
    size: 70,
    startY: 275,
    startX: 40,
    waveAmplitude: 130,
    waveFrequency: 1.9,
    phaseOffset: Math.PI / 2,
    scrollDistance: 58,
    rotationDirection: 1,
    rotationPauses: [0.35, 0.7],
    maxRotation: 360,
    floatDuration: 5.1,
    floatAmplitude: 20,
    floatDelay: 0.2,
    breatheMin: 0.92,
    breatheMax: 1.08,
    breatheDuration: 5.6,
    glowIntensity: 0.72,
  },
  {
    id: "shape-8",
    variant: "clover",
    color: "secondary",
    size: 65,
    startY: 325,
    startX: 65,
    waveAmplitude: 100,
    waveFrequency: 2.4,
    phaseOffset: Math.PI,
    scrollDistance: 52,
    rotationDirection: -1,
    rotationPauses: [0.2, 0.5, 0.85],
    maxRotation: 280,
    floatDuration: 4.7,
    floatAmplitude: 18,
    floatDelay: 0.6,
    breatheMin: 0.94,
    breatheMax: 1.06,
    breatheDuration: 5,
    glowIntensity: 0.68,
  },
  {
    id: "shape-9",
    variant: "gooey-star",
    color: "accent",
    size: 75,
    startY: 375,
    startX: 25,
    waveAmplitude: 150,
    waveFrequency: 1.7,
    phaseOffset: Math.PI / 3,
    scrollDistance: 62,
    rotationDirection: 1,
    rotationPauses: [0.4, 0.75],
    maxRotation: 360,
    floatDuration: 5.4,
    floatAmplitude: 22,
    floatDelay: 0.1,
    breatheMin: 0.91,
    breatheMax: 1.09,
    breatheDuration: 6,
    glowIntensity: 0.8,
  },
  {
    id: "shape-10",
    variant: "pinwheel",
    color: "primary",
    size: 55,
    startY: 425,
    startX: 85,
    waveAmplitude: 95,
    waveFrequency: 3.1,
    phaseOffset: Math.PI / 5,
    scrollDistance: 46,
    rotationDirection: -1,
    rotationPauses: [0.3, 0.6],
    maxRotation: 240,
    floatDuration: 4,
    floatAmplitude: 16,
    floatDelay: 1,
    breatheMin: 0.96,
    breatheMax: 1.04,
    breatheDuration: 4.5,
    glowIntensity: 0.5,
  },
  {
    id: "shape-11",
    variant: "four-point",
    color: "secondary",
    size: 60,
    startY: 475,
    startX: 50,
    waveAmplitude: 85,
    waveFrequency: 2,
    phaseOffset: Math.PI / 2,
    scrollDistance: 44,
    rotationDirection: 1,
    rotationPauses: [0.45, 0.8],
    maxRotation: 180,
    floatDuration: 3.7,
    floatAmplitude: 13,
    floatDelay: 0.3,
    breatheMin: 0.9,
    breatheMax: 1.1,
    breatheDuration: 6,
    glowIntensity: 0.58,
  },
  {
    id: "shape-12",
    variant: "soft-star",
    color: "accent",
    size: 68,
    startY: 525,
    startX: 10,
    waveAmplitude: 120,
    waveFrequency: 2.6,
    phaseOffset: Math.PI / 4,
    scrollDistance: 56,
    rotationDirection: -1,
    rotationPauses: [0.3, 0.65],
    maxRotation: 300,
    floatDuration: 5,
    floatAmplitude: 19,
    floatDelay: 0.7,
    breatheMin: 0.93,
    breatheMax: 1.07,
    breatheDuration: 5.2,
    glowIntensity: 0.7,
  },
  {
    id: "shape-13",
    variant: "clover",
    color: "primary",
    size: 72,
    startY: 575,
    startX: 70,
    waveAmplitude: 140,
    waveFrequency: 1.8,
    phaseOffset: Math.PI,
    scrollDistance: 60,
    rotationDirection: 1,
    rotationPauses: [0.25, 0.6, 0.85],
    maxRotation: 340,
    floatDuration: 5.3,
    floatAmplitude: 21,
    floatDelay: 0.4,
    breatheMin: 0.92,
    breatheMax: 1.08,
    breatheDuration: 5.8,
    glowIntensity: 0.78,
  },
  {
    id: "shape-14",
    variant: "gooey-star",
    color: "secondary",
    size: 58,
    startY: 590,
    startX: 30,
    waveAmplitude: 105,
    waveFrequency: 2.3,
    phaseOffset: Math.PI / 6,
    scrollDistance: 50,
    rotationDirection: -1,
    rotationPauses: [0.35, 0.7],
    maxRotation: 260,
    floatDuration: 4.4,
    floatAmplitude: 17,
    floatDelay: 0.9,
    breatheMin: 0.94,
    breatheMax: 1.06,
    breatheDuration: 5,
    glowIntensity: 0.62,
  },
  {
    id: "shape-15",
    variant: "pinwheel",
    color: "accent",
    size: 66,
    startY: 625,
    startX: 55,
    waveAmplitude: 125,
    waveFrequency: 2,
    phaseOffset: Math.PI / 3,
    scrollDistance: 58,
    rotationDirection: 1,
    rotationPauses: [0.4, 0.75],
    maxRotation: 360,
    floatDuration: 5.6,
    floatAmplitude: 23,
    floatDelay: 0.2,
    breatheMin: 0.91,
    breatheMax: 1.09,
    breatheDuration: 6,
    glowIntensity: 0.82,
  },
  {
    id: "shape-16",
    variant: "four-point",
    color: "secondary",
    size: 60,
    startY: 690,
    startX: 40,
    waveAmplitude: 90,
    waveFrequency: 3,
    phaseOffset: Math.PI / 2,
    scrollDistance: 44,
    rotationDirection: 1,
    rotationPauses: [0.45, 0.8, 0.95],
    maxRotation: 180,
    floatDuration: 3.7,
    floatAmplitude: 13,
    floatDelay: 0.3,
    breatheMin: 0.9,
    breatheMax: 1.1,
    breatheDuration: 6,
    glowIntensity: 0.58,
  },
  {
    id: "shape-17",
    variant: "cross-star",
    color: "primary",
    size: 65,
    startY: 725,
    startX: 15,
    waveAmplitude: 95,
    waveFrequency: 3.1,
    phaseOffset: Math.PI / 2,
    scrollDistance: 46,
    rotationDirection: -1,
    rotationPauses: [0.3, 0.6, 0.9],
    maxRotation: 360,
    floatDuration: 4,
    floatAmplitude: 16,
    floatDelay: 1,
    breatheMin: 0.96,
    breatheMax: 1.04,
    breatheDuration: 4.5,
    glowIntensity: 0.5,
  },
  {
    id: "shape-18",
    variant: "soft-star",
    color: "secondary",
    size: 70,
    startY: 800,
    startX: 70,
    waveAmplitude: 120,
    waveFrequency: 3.2,
    phaseOffset: Math.PI / 5,
    scrollDistance: 56,
    rotationDirection: -1,
    rotationPauses: [0.3, 0.65, 0.8],
    maxRotation: 360,
    floatDuration: 5,
    floatAmplitude: 19,
    floatDelay: 0.7,
    breatheMin: 0.93,
    breatheMax: 1.07,
    breatheDuration: 5.2,
    glowIntensity: 0.7,
  },
];
